version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./todo_list_backend
    container_name: todo_backend
    depends_on:
      - postgres
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PORT: 8080
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
